services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PORT=5433
      - PGPORT=5433
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5433'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-nest-app:latest
    container_name: nest-docker-postgres
    environment:
      - PORT=4000
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5433
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - JWT_SECRET=dfgdfg
      - JWT_EXPIRATION_TIME=24h
      - NODE_ENV=development
      - SALT_ROUNDS=10
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
    # volumes:
    #   - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - db
